name: Build pyorbbecsdk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11==2.11.0 pybind11-global==2.11.0 wheel

    - name: Download Orbbec SDK v2.4.8
      shell: pwsh
      run: |
        curl -L -o sdk.zip "https://github.com/orbbec/OrbbecSDK_v2/releases/download/v2.4.8/OrbbecSDK_v2.4.8_202507032159_ec8e346_win_x64.zip"
        if (-Not (Test-Path "sdk")) { New-Item -ItemType Directory -Path "sdk" }
        Expand-Archive -Path sdk.zip -DestinationPath sdk

    - name: Configure CMake
      run: cmake -S . -B build -DPYBIND11_PYTHON_VERSION=${{ matrix.python-version }} -DOrbbecSDK_DIR="${{ github.workspace }}\\sdk"

    - name: Build
      run: cmake --build build --config Release

    - name: Build Python Wheel
      run: python setup.py bdist_wheel

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyorbbecsdk-win-${{ matrix.python-version }}
        path: dist/*.whl
